# C++ build
language: cpp
compiler:
    - gcc
    - clang
#before_install:
#  - sudo apt-get install cmake
before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make  


# Python build
language: python
python:
  - "2.7"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install swig
install:
  - python setup.py build
#  - "pip install ."

